import { NextResponse } from 'next/server';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export const maxDuration = 60;

const SEV_COLORS = {
  critical: rgb(0.7, 0.05, 0.05),
  high: rgb(0.85, 0.3, 0.05),
  medium: rgb(0.85, 0.65, 0.05),
  low: rgb(0.2, 0.45, 0.85),
  info: rgb(0.45, 0.45, 0.45),
};

function esc(s) {
  return String(s == null ? '' : s).replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

// crude line wrap for Helvetica 10pt (~5.4px per char at this width)
function wrap(text, max = 92) {
  const out = [];
  for (const line of String(text || '').split('\n')) {
    if (line.length <= max) { out.push(line); continue; }
    let cur = '';
    for (const w of line.split(/\s+/)) {
      if ((cur + ' ' + w).trim().length > max) { out.push(cur); cur = w; }
      else cur = (cur + ' ' + w).trim();
    }
    if (cur) out.push(cur);
  }
  return out;
}

function mdReport(d) {
  const host = (() => { try { return new URL(d.finalTarget || d.target).host; } catch { return 'target'; } })();
  const date = new Date().toISOString().slice(0, 16).replace('T', ' ');
  const L = [];
  L.push(`# Big Bounty — Security Assessment: ${host}`);
  L.push('');
  L.push(`- **Target:** ${d.target}`);
  if (d.finalTarget && d.finalTarget !== d.target) L.push(`- **Final URL:** ${d.finalTarget}`);
  L.push(`- **Scan mode:** ${d.scanMode || 'basic'}`);
  L.push(`- **Date:** ${date}`);
  if (d.httpStatus) L.push(`- **HTTP status:** ${d.httpStatus}`);
  L.push('');
  const s = d.summary || {};
  L.push(`## Executive Summary`);
  L.push('');
  L.push(`| Severity | Count |`);
  L.push(`|---|---|`);
  L.push(`| CRITICAL | ${s.critical || 0} |`);
  L.push(`| HIGH | ${s.high || 0} |`);
  L.push(`| MEDIUM | ${s.medium || 0} |`);
  L.push(`| LOW | ${s.low || 0} |`);
  L.push(`| INFO | ${s.info || 0} |`);
  L.push('');
  L.push(`**Total findings:** ${(d.findings || []).length} · **Tools used:** ${(d.toolsUsed || []).join(', ')}`);
  L.push('');
  L.push(`## Findings`);
  const order = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
  const fs2 = [...(d.findings || [])].sort((a, b) => (order[a.severity] ?? 9) - (order[b.severity] ?? 9));
  fs2.forEach((f, i) => {
    L.push('');
    L.push(`### ${i + 1}. [${String(f.severity).toUpperCase()}] ${f.title}`);
    L.push('');
    L.push(`- **Tool:** ${f.tool}`);
    if (f.fix) L.push(`- **Recommendation:** ${f.fix}`);
    if (f.curl) { L.push('- **Reproduce:**'); L.push('```bash'); L.push(f.curl); L.push('```'); }
    if (f.evidence) { L.push('- **Evidence:**'); L.push('```json'); L.push(JSON.stringify(f.evidence, null, 2).slice(0, 1200)); L.push('```'); }
  });
  L.push('');
  L.push('---');
  L.push('_Generated by Big Bounty (big-bounty.vercel.app). Findings are observations from automated testing — verify each one before acting. Only test targets you are authorized to test._');
  return L.join('\n');
}

export async function POST(request) {
  let scan;
  try {
    scan = await request.json();
  } catch {
    return NextResponse.json({ error: 'Send the scan result JSON in the request body' }, { status: 400 });
  }
  if (!scan || typeof scan !== 'object' || !scan.target) {
    return NextResponse.json({ error: 'Invalid scan result payload' }, { status: 400 });
  }

  const url = new URL(request.url);
  const format = (url.searchParams.get('format') || 'pdf').toLowerCase();
  const host = (() => { try { return new URL(scan.finalTarget || scan.target).host; } catch { return 'target'; } })();
  const fname = `bigbounty-${host.replace(/[^a-z0-9.-]/gi, '-')}-${new Date().toISOString().slice(0, 10)}`;

  if (format === 'md') {
    return new NextResponse(mdReport(scan), {
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Content-Disposition': `attachment; filename="${fname}.md"`,
        'Cache-Control': 'no-store',
      },
    });
  }

  // ---- PDF ----
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont('Helvetica');
  const bold = await pdf.embedFont('Helvetica-Bold');
  const mono = await pdf.embedFont('Courier');

  const W = 612, H = 792, M = 54;
  let page = pdf.addPage([W, H]);
  let y = H - M;
  const ink = rgb(0.1, 0.1, 0.12);

  const newPage = () => { page = pdf.addPage([W, H]); y = H - M; };
  const need = (n) => { if (y - n < M + 30) newPage(); };

  function text(str, { font = ink ? undefined : undefined, f = 'reg', size = 9.5, color = ink, x = M, max = W - 2 * M, gap = 4 } = {}) {
    const useFont = f === 'bold' ? bold : f === 'mono' ? mono : font;
    for (const line of wrap(str, Math.floor(max / (size * 0.56)))) {
      need(size + gap);
      page.drawText(line, { x, y, size, font: useFont, color });
      y -= size + gap;
    }
  }
  function heading(str, size = 15) {
    need(size + 14);
    y -= 8;
    page.drawText(esc(str).slice(0, 110), { x: M, y, size, font: bold, color: rgb(0.05, 0.05, 0.08) });
    y -= size + 8;
    page.drawLine({ start: { x: M, y: y + 4 }, end: { x: W - M, y: y + 4 }, thickness: 0.8, color: rgb(0.75, 0.75, 0.8) });
    y -= 10;
  }

  // Cover header
  page.drawRectangle({ x: 0, y: H - 110, width: W, height: 110, color: rgb(0.06, 0.06, 0.1) });
  page.drawText('BIG BOUNTY', { x: M, y: H - 52, size: 24, font: bold, color: rgb(1, 1, 1) });
  page.drawText('SECURITY ASSESSMENT REPORT', { x: M, y: H - 74, size: 10, font: bold, color: rgb(0.65, 0.7, 0.85) });
  page.drawText(`Generated ${new Date().toISOString().slice(0, 16).replace('T', ' ')} UTC`, { x: M, y: H - 94, size: 8.5, color: rgb(0.6, 0.62, 0.7) });
  y = H - 130;

  const s = scan.summary || {};
  const findings = [...(scan.findings || [])].sort((a, b) => {
    const order = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
    return (order[a.severity] ?? 9) - (order[b.severity] ?? 9);
  });

  heading('Assessment Overview', 14);
  text(`Target: ${scan.target}`, { f: 'bold', size: 10 });
  if (scan.finalTarget && scan.finalTarget !== scan.target) text(`Resolved to: ${scan.finalTarget}`, { size: 9 });
  text(`Scan mode: ${String(scan.scanMode || 'basic').toUpperCase()}    HTTP status: ${scan.httpStatus ?? 'n/a'}    Duration: ${scan.durationMs ? Math.round(scan.durationMs / 1000) + 's' : 'n/a'}`, { size: 9.5 });
  text(`Tools: ${(scan.toolsUsed || []).join(', ') || 'n/a'}`, { size: 9 });

  y -= 6; need(90);
  page.drawText('Findings by severity', { x: M, y, size: 11, font: bold, color: ink }); y -= 16;
  const rows = [['CRITICAL', s.critical || 0], ['HIGH', s.high || 0], ['MEDIUM', s.medium || 0], ['LOW', s.low || 0], ['INFO', s.info || 0]];
  const total = rows.reduce((n, r) => n + r[1], 0);
  for (const [name, count] of rows) {
    const barW = total ? Math.max(2, (count / total) * 320) : 0;
    page.drawRectangle({ x: M + 90, y: y - 2, width: 320, height: 10, color: rgb(0.93, 0.93, 0.96) });
    if (count > 0) page.drawRectangle({ x: M + 90, y: y - 2, width: barW, height: 10, color: SEV_COLORS[name.toLowerCase()] });
    page.drawText(name, { x: M, y, size: 9, font: bold, color: ink });
    page.drawText(String(count), { x: M + 90 + 328, y, size: 9.5, font: bold, color: ink });
    y -= 17;
  }
  y -= 6;

  heading(`Findings (${findings.length})`, 14);
  if (!findings.length) text('No findings recorded for this scan.', { size: 10 });

  findings.forEach((f, i) => {
    need(70);
    y -= 6;
    const col = SEV_COLORS[String(f.severity).toLowerCase()] || SEV_COLORS.info;
    page.drawRectangle({ x: M, y: y - 4, width: 4, height: 16, color: col });
    page.drawText(`#${i + 1}  ${String(f.severity).toUpperCase()}`, { x: M + 10, y, size: 10, font: bold, color: col });
    page.drawText(`[${f.tool}]`, { x: M + 80, y, size: 8.5, color: rgb(0.4, 0.4, 0.48) });
    y -= 14;
    text(f.title, { f: 'bold', size: 10 });
    if (f.evidence) {
      text('Evidence:', { f: 'bold', size: 8.5, color: rgb(0.35, 0.35, 0.4) });
      text(JSON.stringify(f.evidence, null, 1).slice(0, 900), { f: 'mono', size: 7.5, color: rgb(0.25, 0.25, 0.3) });
    }
    if (f.curl) {
      text('Reproduce (PoC):', { f: 'bold', size: 8.5, color: rgb(0.35, 0.35, 0.4) });
      text(f.curl.slice(0, 500), { f: 'mono', size: 7.5, color: rgb(0.15, 0.3, 0.15) });
    }
    if (f.fix) {
      text(`Fix: ${f.fix}`.slice(0, 700), { size: 8.5, color: rgb(0.3, 0.3, 0.38) });
    }
  });

  // Footer on every page
  const pages = pdf.getPages();
  pages.forEach((pg, idx) => {
    pg.drawText(`Big Bounty · automated security assessment · page ${idx + 1}/${pages.length}`, { x: M, y: 30, size: 7.5, color: rgb(0.55, 0.55, 0.6) });
    pg.drawText('Findings are observations — verify before acting. Test only authorized targets.', { x: W - M - 250, y: 30, size: 7.5, color: rgb(0.55, 0.55, 0.6) });
  });

  const bytes = await pdf.save();
  return new NextResponse(Buffer.from(bytes), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${fname}.pdf"`,
      'Cache-Control': 'no-store',
    },
  });
}